### ISSUE TITLE
Uses or overrides a deprecated API

### ISSUE THREAD

**Issue by vemla-solutions** [yangming1009/volume_watcher#6]
**System:**
Flutter Channel stable, 2.0.1
volume_watcher: ^1.3.1
Android

**Error:**
When generating the build I get:
Note: \flutter\.pub-cache\hosted\pub.dartlang.org\volume_watcher-1.3.1\android\src\main\java\com\magugi\volume_watcher\VolumeWatcherPlugin.java uses or overrides a
deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by RasmusGodske** [comment]
I'm getting the same error

**Comment by yangming1009** [comment]
has fixed.
